FizzBuzzプログラムを作成
NorisukeArmStrong/ruby-practices pull request #1
Opened 2023-08-09 01:31 UTC by NorisukeArmStrong

2023-08-14 23:46 UTC, maedana commented
ファイル名が`FizzBuzz-prc`となっており、パスカルケースとケバブケースが混ざったような命名になっているのがおかしいですね。Rubyのファイル名は特別な理由がない限りスネークケースで命名しましょう。

2023-08-14 23:47 UTC, summertree128 approved these changes

2023-08-14 23:48 UTC, maedana commented on 01.fizzbuzz/FizzBuzz-prc.rb
> +while number < 20
プログラムでミスがあるときに無限ループするリスクのある`while`は避けたいですね。今回は20回ループすることが決まっているので別の手段で対応してみて欲しいです。もし難しければ追加でヒント出しますのでFBCの提出物のコメント欄でその旨お知らせください :pray:

2023-08-14 23:50 UTC, summertree128 requested changes
間違えてコメントなしでapproveしてしまった & @maedana さんと被っちゃったので取り消します 🙏

2023-08-17 00:37 UTC, maedana approved these changes

2023-08-17 00:41 UTC, maedana requested changes
ファイル名ですが、FizzBuzzですとパスカルケースなのでまだおかしいですねー。前回書いた通りですけど`スネークケース`にしましょう。

2023-08-21 03:32 UTC, maedana approved these changes

2023-09-03 04:48 UTC, merged